mutation createUser($firstName: String!, $lastName: String!, $uiLanguage: String!){
    createUser(firstName: $firstName, lastName: $lastName, uiLanguage: $uiLanguage){
		userId
        firstName
        lastName
        uiLanguage
		checkList{
			description
		}
    }
}