version: "3.6"
services:
  server:
    image: server
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./server:/app
      - dist:/app/dist
  client:
    image: client
    build: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
      - dist:/app/dist
volumes:
  dist:
